version: "3"
services:
  prisma:
    container_name: go-prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "7000:7000"
    environment:
      PRISMA_CONFIG: |
        port: 7000
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: ${PRISMA_SECRET}
        databases:
          default:
            connector: postgres
            host: ${HOST_DB}
            database: ${PG_DB}
            schema: public
            user: ${PG_USER}
            password: ${PG_PASSWORD}
            ssl: false
            rawAccess: true
            port: '7001'
            migrations: true%